model:
  name: "vol"
  kind: "mpii"
  volume_aggregation_method: "softmax"

  init_weights: true
  checkpoint: "./data/pretrained/human36m/human36m_vol_softmax_10-08-2019/checkpoints/0040/weights.pth"

  use_gt_pelvis: false

  cuboid_side: 2500.0

  volume_size: 64
  volume_multiplier: 1.0
  volume_softmax: true

  heatmap_softmax: true
  heatmap_multiplier: 100.0

  backbone:
    name: "resnet152"
    style: "simple"

    init_weights: true
    checkpoint: "./data/pretrained/human36m/pose_resnet_4.5_pixels_human36m.pth"

    num_joints: 17
    num_layers: 152